{{-- Autogenerated with `swagger:generate`. Do not modify this file directly. --}}
{
    "swagger": "2.0",
    "info": {
        "title": "Leadgen API",
        "version": "0.1-beta"
    },
    "host": "{{ $host }}",
    "basePath": "/api/v1",
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/customer": {
            "get": {
                "tags": [
                    "customer"
                ],
                "summary": "Retrieve a list of customers",
                "description": "Retrieves a list of customers with pagination support.",
                "operationId": "customer.index",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page to be retrieved",
                        "required": false,
                        "type": "integer",
                        "default": 1
                    },
                    {
                        "name": "query",
                        "in": "query",
                        "description": "Segment query to filter customers. In json format",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer data",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Display a listing of the resource.",
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Customer"
                                    }
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/customer/{id}": {
            "get": {
                "tags": [
                    "customer"
                ],
                "summary": "Retrieve a specific customer",
                "description": "You can retrieve a customer by it's _id or email",
                "operationId": "customer.show",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id or email of the customer to be retrieved",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer data",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Retrieve a specific customer.",
                                    "$ref": "#/definitions/Customer"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Customer not found",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/interaction/pulse": {
            "get": {
                "tags": [
                    "interaction"
                ],
                "summary": "Retrieve a list of interactions of the last minute",
                "description": "Retrieves a list of interactions of the last minute.",
                "operationId": "interaction.pulse",
                "responses": {
                    "200": {
                        "description": "Summary of latest interactions",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Author as key and interaction type as value.",
                                    "type": "array",
                                    "items": {
                                        "type": "object"
                                    }
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/interaction": {
            "post": {
                "tags": [
                    "interaction"
                ],
                "summary": "Stores a new interaction",
                "description": "Stores a new customer interaction.",
                "operationId": "interaction.store",
                "parameters": [
                    {
                        "name": "interaction",
                        "in": "body",
                        "description": "Interaction to be stored",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Interaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Interaction data",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Stores a new resource.",
                                    "$ref": "#/definitions/Interaction"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/interactionType": {
            "get": {
                "tags": [
                    "interactionType"
                ],
                "summary": "Retrieve a list of interactionTypes",
                "description": "Retrieves a list of interactionTypes with pagination support.",
                "operationId": "interactionType.index",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page to be retrieved",
                        "required": false,
                        "type": "integer",
                        "default": 1
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of existent interactionTypes",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Display a listing of the resource.",
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/InteractionType"
                                    }
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "interactionType"
                ],
                "summary": "Creates a new interactionType",
                "description": "Creates a new interactionType entity.",
                "operationId": "interactionType.store",
                "parameters": [
                    {
                        "name": "interactionType",
                        "in": "body",
                        "description": "Segment to be created",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InteractionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The newly created interactionType",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Store a newly created resource in storage.",
                                    "$ref": "#/definitions/InteractionType"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/interactionType/{id}": {
            "get": {
                "tags": [
                    "interactionType"
                ],
                "summary": "Retrieve a specific interactionType",
                "description": "You can retrieve a interactionType by it's _id or email",
                "operationId": "interactionType.show",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id of the interactionType to be retrieved",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Segment data",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Display the specified resource.",
                                    "$ref": "#/definitions/InteractionType"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Segment not found",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "interactionType"
                ],
                "summary": "Updates a interactionType",
                "description": "Updates a interactionType entity.",
                "operationId": "interactionType.update",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id of the interactionType to be updated",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interactionType",
                        "in": "body",
                        "description": "Values that will overwrite the attributes of the interactionType if the id on the url.",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InteractionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The updated interactionType in it's new state.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Update the specified resource in storage.",
                                    "$ref": "#/definitions/InteractionType"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Segment not found. A interactionType with the given id was not found to be updated.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request. If was not possible to update the interactionType.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "interactionType"
                ],
                "summary": "Deletes an existing interactionType",
                "description": "Deletes a interactionType.",
                "operationId": "interactionType.delete",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id of the interactionType to be deleted",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Segment not found. A interactionType with the given id was not found to be deleted.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request. If was not possible to delete the interactionType.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/segment": {
            "get": {
                "tags": [
                    "segment"
                ],
                "summary": "Retrieve a list of segments",
                "description": "Retrieves a list of segments with pagination support.",
                "operationId": "segment.index",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page to be retrieved",
                        "required": false,
                        "type": "integer",
                        "default": 1
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of existent segments",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Display a listing of the resource.",
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Segment"
                                    }
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "segment"
                ],
                "summary": "Creates a new segment",
                "description": "Creates a new segment entity.",
                "operationId": "segment.store",
                "parameters": [
                    {
                        "name": "segment",
                        "in": "body",
                        "description": "Segment to be created",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Segment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The newly created segment",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Store a newly created resource in storage.",
                                    "$ref": "#/definitions/Segment"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/segment/{id}": {
            "get": {
                "tags": [
                    "segment"
                ],
                "summary": "Retrieve a specific segment",
                "description": "You can retrieve a segment by it's _id or email",
                "operationId": "segment.show",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id of the segment to be retrieved",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Segment data",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Display the specified resource.",
                                    "$ref": "#/definitions/Segment"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Segment not found",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "segment"
                ],
                "summary": "Updates a segment",
                "description": "Updates a segment entity.",
                "operationId": "segment.update",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id of the segment to be updated",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "segment",
                        "in": "body",
                        "description": "Values that will overwrite the attributes of the segment if the id on the url.",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Segment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The updated segment in it's new state.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "Update the specified resource in storage.",
                                    "$ref": "#/definitions/Segment"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Segment not found. A segment with the given id was not found to be updated.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request. If was not possible to update the segment.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "segment"
                ],
                "summary": "Deletes an existing segment",
                "description": "Deletes a segment.",
                "operationId": "segment.delete",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "_id of the segment to be deleted",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Segment not found. A segment with the given id was not found to be deleted.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad request. If was not possible to delete the segment.",
                        "schema": {
                            "properties": {
                                "status": {
                                    "description": "Response status",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Array of error messages",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Customer": {
            "properties": {
                "_id": {
                    "description": "Unique identifier of the customer. (Generated automatically)",
                    "type": "string"
                },
                "docNumber": {
                    "description": "An document number that identify this customer. May be an CRM number for example.",
                    "type": "string"
                },
                "email": {
                    "description": "Email of the customer.",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the customer.",
                    "type": "string"
                },
                "interactions": {
                    "description": "Interactions that this customer has made.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Interaction"
                    }
                },
                "location": {
                    "description": "Tells in which location the customer was in his last interaction.",
                    "type": "string",
                    "default": "web"
                },
                "segments": {
                    "description": "_id of the segments that the customer is part of.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "aggregated": {
                    "description": "Pre aggregated or calculated values that may be later filled.",
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            },
            "type": "object"
        },
        "Interaction": {
            "required": [
                "author",
                "interaction"
            ],
            "properties": {
                "_id": {
                    "description": "Unique identifier of the interaction. (Generated automatically)",
                    "type": "string"
                },
                "author": {
                    "description": "Email or docNumber of the customer that made the interaction.",
                    "type": "string"
                },
                "authorId": {
                    "description": "Unique identifier of the customer that made the interaction. (Generated based in the `author` property)",
                    "type": "string"
                },
                "interaction": {
                    "description": "Unique identifier of the `InteractionType` that describes this interaction.",
                    "type": "string"
                },
                "params": {
                    "description": "The params of the interaction. A set of key-value properties that should follow the params described in the `InteractionType`.",
                    "type": "object"
                },
                "channel": {
                    "description": "Tells throught which channel the customer did that interaction.",
                    "type": "string"
                },
                "location": {
                    "description": "Tells in which location the customer was.",
                    "type": "string",
                    "default": "web"
                },
                "acknowledged": {
                    "description": "Tells if the given `Interaction` have already been indexed in Elasticsearch.",
                    "type": "boolean",
                    "default": false
                }
            },
            "type": "object"
        },
        "InteractionType": {
            "required": [
                "name",
                "slug",
                "params"
            ],
            "properties": {
                "_id": {
                    "description": "Unique identifier. (Generated automatically)",
                    "type": "string"
                },
                "name": {
                    "description": "The name of the interaction type.",
                    "type": "string"
                },
                "slug": {
                    "description": "Slug that identifies the given interaction type. No space or special characters are allowed.",
                    "type": "string"
                },
                "params": {
                    "description": "Params of the given interaction",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Param"
                    }
                }
            },
            "type": "object"
        },
        "Param": {
            "required": [
                "name",
                "type",
                "required"
            ],
            "properties": {
                "_id": {
                    "description": "Unique identifier. (Generated automatically)",
                    "type": "string"
                },
                "name": {
                    "description": "Name of parameter. No space or special characters are allowed.",
                    "type": "string"
                },
                "type": {
                    "description": "Type of the parameter",
                    "type": "string"
                },
                "required": {
                    "description": "Tells if the parameter is required.",
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "Ruleset": {
            "required": [
                "rules"
            ],
            "properties": {
                "_id": {
                    "description": "Unique identifier of the rule set. (Generated automatically)",
                    "type": "string"
                },
                "rules": {
                    "description": "Rules that determines if a customers is part of the segment.",
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            },
            "type": "object"
        },
        "Segment": {
            "required": [
                "name",
                "slug",
                "ruleset"
            ],
            "properties": {
                "_id": {
                    "description": "Unique identifier of the segment. (Generated automatically)",
                    "type": "string"
                },
                "name": {
                    "description": "Name to identify the segment.",
                    "type": "string"
                },
                "slug": {
                    "description": "A clean string to identify the segment.",
                    "type": "string"
                },
                "ruleset": {
                    "description": "The ruleset that determines if a customers is part of the segment.",
                    "type": "object",
                    "$ref": "#/definitions/Ruleset"
                },
                "additionInterval": {
                    "description": "Interval (in cron-job format) to test and add new customers are part of the given segment.",
                    "type": "string",
                    "default": "30 0 * * * *"
                },
                "removalInterval": {
                    "description": "Interval (in cron-job format) to re-test and remove users from the segment.",
                    "type": "string",
                    "default": "0 0 * * * *"
                },
                "triggers": {
                    "description": "An array of triggers entities that will be executed whenever a Customer joins or leaves a segment.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Trigger"
                    }
                }
            },
            "type": "object"
        },
        "Trigger": {
            "required": [
                "type"
            ],
            "properties": {
                "_id": {
                    "description": "Unique identifier of the rule set. (Generated automatically)",
                    "type": "string"
                },
                "type": {
                    "description": "Identifies which trigger/logic will be executed.",
                    "type": "string"
                },
                "settings": {
                    "description": "A settings object that will be read in trigger excecution.",
                    "type": "object"
                }
            },
            "type": "object"
        }
    }
}